// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCatSYHuALxdf-wnWrbehKFiA6qq_G6h-0',
    appId: '1:961139471812:android:f3f9724c529af75112a091',
    messagingSenderId: '961139471812',
    projectId: 'film-track',
    databaseURL: 'https://film-track-default-rtdb.firebaseio.com',
    storageBucket: 'film-track.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhOK34FW2i-3wRDQzoAAY2J6UnkTGWRxc',
    appId: '1:961139471812:ios:75603ba5e8d67ee812a091',
    messagingSenderId: '961139471812',
    projectId: 'film-track',
    databaseURL: 'https://film-track-default-rtdb.firebaseio.com',
    storageBucket: 'film-track.appspot.com',
    iosClientId: '961139471812-pbjj529k7acopkfg230bk8r9eqncus35.apps.googleusercontent.com',
    iosBundleId: 'com.example.filmtrack',
  );
}